예외처리
 - JavaScript에는 코드 실행 중에 예기치 못한 에러가 발생했을 때 이로부터 코드의 실행 흐름을 복구할 수 있는 기능이 내장되어 있다. 
   이런 기능을 일러 예외 처리(exception handling)라고 한다.

 - try...catch...finally 구문을 사용하면 에러가 나더라도 코드의 실행을 지속할 수 있다.
   try {
    
   } catch(e) {

   } finally {

   }

 - throw를 통해 예외를 발생시킬 수 있다.
   throw "var is empty";